executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: imageUrl
    description: "%url-of-the-source-image-to-edit-must-be-a-valid-uri-pointing-to%"
    json_schema:
      type: string
      format: uri
    nullable: false
  - handle: prompt
    description: "%text-instructions-describing-the-desired-edits-specify-changes-a%"
    json_schema:
      type: string
      ui:widget: text
    nullable: false
  - group: Optional Settings
    collapsed: true
  - handle: aspectRatio
    description: "%output-image-aspect-ratio-options-range-from-ultrawide-21-9-to-p%"
    json_schema:
      enum:
        - 21:9
        - 16:9
        - 3:2
        - 4:3
        - 5:4
        - 1:1
        - 4:5
        - 3:4
        - 2:3
        - 9:16
    value: 3:2
    nullable: true
  - handle: resolution
    description: "%output-resolution-quality-1k-standard-2k-high-or-4k-ultra-high-d%"
    json_schema:
      enum:
        - 1K
        - 2K
        - 4K
      ui:options:
        {}
    value: 1K
    nullable: true
outputs_def:
  - handle: imageUrl
    description: "%url-of-the-edited-image-points-to-the-modified-image-file-with-a%"
    json_schema:
      type: string
    nullable: false
icon: ":twemoji:banana:"
title: "%editor%"
description: "%modifies-existing-images-based-on-text-instructions-using-ai-pow%"
