executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: content
    description: "%research-content-or-method-description-to-find-relevant-referenc%"
    json_schema:
      type: string
      ui:widget: text
    nullable: false
  - handle: caption
    description: "%optional-caption-providing-additional-context-for-retrieval-help%"
    json_schema:
      type: string
    value:
    nullable: true
outputs_def:
  - handle: references
    description: "%array-of-matched-reference-objects-each-contains-id-unique-ident%"
    json_schema:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          visual_intent:
            type: string
          content:
            type: string
          path_to_gt_image:
            type: string
    nullable: false
icon: ":twemoji:magnifying-glass-tilted-left:"
title: "%retriever%"
description: "%searches-curated-diagram-collection-to-find-visually-similar-ref%"
